name: Python CI
run-name: ${{ github.actor }}-${{ github.ref_name }}

env:
  PYTHON_VERSION: 3.8

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      name: Setup Python ${{ env.PYTHON_VERSION }}
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py runserver


    - name: Lint
      run: |
        cd ../
        flake8 . --show-source --statistics
    - name: Check Complexity
      run: |
        cd ../
        flake8 . --statistics --max-complexity=10 --exit-zero

    - name: Run unit tests with pytest
      run: |
        pytest -v ./accounts/tests.py --cov=. --cov-report=term-missing --cov-report=json
        pytest -v ./lists/tests.py --cov=. --cov-report=term-missing --cov-report=json
        pytest -v ./api/tests.py --cov=. --cov-report=term-missing --cov-report=json